FROM python:3.8

# set a directory for the app
WORKDIR /code

# copy requirements file
COPY ./requirements.txt /code/requirements.txt

# install dependencies
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# copy API files
COPY ./app /code/app

# run the command
CMD ["fastapi", "run", "app/main.py", "--port", "8000"]