FROM python:3.8

# set a directory for the app
WORKDIR /code

# copy requirements file
COPY ./requirements.txt /code/requirements.txt

# install dependencies
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# copy API files
COPY ./app /code/app

# copy Test files
COPY ./tests /code/tests

# run the command
CMD ["pytest", "-v", "--html=report.html", "--self-contained-html"]